
# ESP_HOME must point to esp-open-sdk

USER_LIBDIR ?= tweaked-
LWIP_LIB_RELEASE=$(USER_LIBDIR)liblwip2.a
LWIP_INCLUDES_RELEASE=$(USER_LIBDIR)../include/lwip2

all: install

%:
	@make -f makefiles/Makefile.build-lwip2 \
			SDK=$(ESP_HOME)/sdk \
			LWIP_LIB=liblwip2.a \
			LWIP_LIB_RELEASE=$(LWIP_LIB_RELEASE) \
			LWIP_INCLUDES_RELEASE=$(LWIP_INCLUDES_RELEASE) \
			TOOLS=$(ESP_HOME)/xtensa-lx106-elf/bin/xtensa-lx106-elf- \
			$@
