
# stable MSS: 536..896
# unstable: 1024 1460

%:
	for v6 in 0 1; do \
	for mss in 536 1460; do \
		make -f makefiles/Makefile.build-lwip2 \
			target=arduino \
			SDK=../.. \
			LWIP_ESP=../../lwip/include \
			LWIP_LIB=liblwip$$((2+4*v6))_$$mss.a \
			LWIP_LIB_RELEASE=../../lib/liblwip$$((2+4*v6))_$$mss.a \
			LWIP_INCLUDES_RELEASE=../include \
			TOOLS=../../../xtensa-lx106-elf/bin/xtensa-lx106-elf- \
			TCP_MSS=$$mss LWIP_IPV6=$$v6 BUILD=build-$$mss-v$$((4+2*v6)) \
			$@ ; \
	done; done
