
all: .patched

.patched:
	for p in ../../patches/*.patch; do echo "--------- APPLY PATCH $${p#../../}:"; patch -d .. -p1 < $$p; done
ifeq ($(target),open)
	patch -d .. -p1 < ../../patches/open/sdk-mem-macros.patch
endif
	touch .patched
