ifndef SDK
$(error SDK must point to espressif sdk folder)
endif

ifndef LWIP14_INCLUDE_DIR
$(error LWIP14_INCLUDE_DIR must point to espressif sdk lwip/include)
endif

SRC = $(wildcard glue-esp/*.c)

BUILD_INCLUDES = -I$(BUILD_ROOT) -I$(SDK)/include -I$(LWIP14_INCLUDE_DIR) -I$(ROOT)/glue
BUILD_FLAGS += -DLWIP14GLUE

include makefiles/include/defs.mk
include makefiles/include/rules.mk

-include $(BUILD)/glue-esp/*.d

.DEFAULT: all
