OBJ = $(shell find $(BUILD) -name "*.o")

$(BUILD)/$(LWIP_LIB): $(OBJ)
	$(AR) cru $@ $?

$(BUILD_ROOT)/$(LWIP_LIB): $(BUILD)/$(LWIP_LIB)
	@cp $< $@

all: $(BUILD_ROOT)/$(LWIP_LIB)

include $(ROOT)/makefiles/include/defs.mk
